### ISSUE TITLE
base_url error

### ISSUE THREAD

**Issue by AP1979** [dzt/trimalchio#5]
Hi, really keen to get this working but always crashes with the below error:

![image](https://user-images.githubusercontent.com/32411427/31044521-42c253c2-a614-11e7-8d95-b57add46ebfc.png)
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
/Users/andreas/trimalchio/trimalchio/findItem.js:22
  if (config.base_url.endsWith('.xml')) {
            ^

TypeError: Cannot read property 'base_url' of undefined
    at findItem (/Users/andreas/trimalchio/trimalchio/findItem.js:22:13)
    at startBasicMode (/Users/andreas/trimalchio/index.js:112:3)
    at Timeout.setTimeout (/Users/andreas/trimalchio/index.js:115:16)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by bingbang404** [comment]
I also like who can help?

**Comment by NullFragment** [comment]
+1 here as well
